steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cloudbuilddemo/gke_helloworld:1.0.$REVISION_ID', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cloudbuilddemo/gke_helloworld:1.0.$REVISION_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/hello-web', 'gke_helloworld=gcr.io/cloudbuilddemo/gke_helloworld:1.0.$REVISION_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-web-cluster'